_format_version: "3.0"
plugins:
  - name: response-transformer
    enabled: true
    config:
      add:
        headers:
          - "Strict-Transport-Security:max-age=31536000; includeSubDomains; preload"
