name: Docker central workflow

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    tags:
      - '[vV][0-9]+.[0-9]+.[0-9]+*'

jobs:
  docker:
    uses: folio-org/.github/.github/workflows/docker.yml@master
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push'
    secrets: inherit

