name: Docker central workflow

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    tags:
      - '[vV][0-9]+.[0-9]+.[0-9]+*'

jobs:
  docker:
    uses: folio-org/.github/.github/workflows/docker.yml@v1
    secrets: inherit

