name: Docker central workflow

on:
  - push
  - workflow_dispatch

jobs:
  docker:
    uses: folio-org/.github/.github/workflows/docker.yml@master
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push'
    secrets: inherit

